
'use server';

import { db } from '@/lib/firebase';
import { collection, getDocs, doc, updateDoc, setDoc, addDoc } from 'firebase/firestore';

// Define the User type matching the structure in Firestore and the application
export type UserRole = "User" | "Community Admin" | "General Admin";
export type UserStatus = "Active" | "Restricted";

export type UserSettings = {
  enableBiometrics: boolean;
  theme: 'light' | 'dark' | 'system';
  profileVisible: boolean;
  notifications: {
    email: {
      announcements: boolean;
      investments: boolean;
      withdrawals: boolean;
    };
    push: boolean;
  };
};

export type User = {
  id: string;
  name: string;
  email: string;
  avatarUrl: string;
  role: UserRole;
  status: UserStatus;
  balance: number;
  isTopUser: boolean;
  dateJoined: string;
  community?: string;
};

/**
 * Creates a new user in Firestore.
 * This is used during the signup process.
 * @param userData The essential data for the new user from the signup form.
 */
export async function createUser(userData: Pick<User, 'name' | 'email' | 'community'>): Promise<User> {
    const usersCollection = collection(db, 'users');
    
    const newUser: Omit<User, 'id'> = {
        ...userData,
        avatarUrl: `https://i.pravatar.cc/150?u=${Math.random().toString(36).substring(7)}`,
        role: 'User',
        status: 'Active',
        balance: 0,
        isTopUser: false,
        dateJoined: new Date().toISOString(),
    };

    const docRef = await addDoc(usersCollection, newUser);
    return { id: docRef.id, ...newUser };
}

/**
 * Fetches all users from the "users" collection in Firestore.
 */
export async function getUsers(): Promise<User[]> {
  const usersCollection = collection(db, 'users');
  const userSnapshot = await getDocs(usersCollection);
  const userList = userSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as User));
  
  // Seed data if the collection is empty
  if (userList.length === 0) {
    return seedInitialUsers();
  }

  return userList;
}

/**
 * Updates a user's data in Firestore.
 * @param userId The ID of the user to update.
 * @param data The partial user data to update.
 */
export async function updateUser(userId: string, data: Partial<User>): Promise<void> {
  const userDoc = doc(db, 'users', userId);
  await updateDoc(userDoc, data);
}


/**
 * Seeds the database with initial user data if it's empty.
 */
async function seedInitialUsers(): Promise<User[]> {
    const initialUsers: Omit<User, 'id'>[] = [
      { name: 'Olivia Martin', email: 'olivia.martin@email.com', avatarUrl: 'https://i.pravatar.cc/150?u=a', role: 'User', status: 'Active', balance: 1250.75, isTopUser: true, dateJoined: '2024-07-15', community: 'Northside' },
      { name: 'Jackson Lee', email: 'jackson.lee@email.com', avatarUrl: 'https://i.pravatar.cc/150?u=b', role: 'Community Admin', status: 'Active', balance: 750.00, isTopUser: false, dateJoined: '2024-07-14', community: 'Southside' },
      { name: 'Liam Johnson', email: 'liam@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=c', role: 'User', status: 'Restricted', balance: 300.25, isTopUser: false, dateJoined: '2024-07-12', community: 'Northside' },
      { name: 'Noah Williams', email: 'noah@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=d', role: 'Community Admin', status: 'Active', balance: 5000.00, isTopUser: true, dateJoined: '2024-07-10', community: 'Northside' },
      { name: 'Admin User', email: 'admin@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=e', role: 'General Admin', status: 'Active', balance: 0.00, isTopUser: false, dateJoined: '2024-06-01' },
      { name: 'Ethan Jones', email: 'ethan.jones@email.com', avatarUrl: 'https://i.pravatar.cc/150?u=f', role: 'User', status: 'Active', balance: 250.00, isTopUser: false, dateJoined: '2024-07-18', community: 'Southside' },
    ];

    const seededUsers: User[] = [];
    for (const userData of initialUsers) {
        // In a real app, IDs would be generated by auth or Firestore's addDoc
        const userId = `usr_${(Math.random() + 1).toString(36).substring(7)}`;
        const userDocRef = doc(db, 'users', userId);
        await setDoc(userDocRef, userData);
        seededUsers.push({ id: userId, ...userData });
    }

    console.log('Database seeded with initial users.');
    return seededUsers;
}
